version: '3'
services:
  bookmarks:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    entrypoint: |
      - npm run build:archive:bookmarks
      - npm run archive:bookmarks
  starred_repos:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    entrypoint: |
      - npm run build:archive:starred-repos
      - npm run archive:starred-repos
  tweets:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    entrypoint: |
      - npm run build:archive:tweets
      - npm run archive:tweets
  airtable:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    entrypoint: |
      - npm run build:backup:airtable
      - npm run backup:airtable
