name: Archive Bookmarks

on:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  archive-bookmarks:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node 16.15.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg

      - name: Install yt-dlp
        run: |
          wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
          chmod a+rx /usr/local/bin/yt-dlp

      - name: Compile archive script
        run: npm run build:archive:bookmarks

      - name: Run archive script
        run: npm run archive:bookmarks
        env:
          CI: true
          HASURA_ADMIN_SECRET: ${{secrets.HASURA_ADMIN_SECRET}}
          HASURA_ENDPOINT: ${{secrets.HASURA_ENDPOINT}}
          B2_APP_KEY_ID: ${{secrets.B2_APP_KEY_ID}}
          B2_APP_KEY: ${{secrets.B2_APP_KEY}}
          B2_BUCKET_ID: ${{secrets.B2_BUCKET_ID}}
          B2_BUCKET_NAME: ${{secrets.B2_BUCKET_NAME}}
