name: Archive Bookmarks

on:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  archive-bookmarks:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node 15.13.0
        uses: actions/setup-node@v2
        with:
          node-version: 15.13.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install ffmpeg
        run: npm i @ffmpeg/core

      - name: Compile
        run: npm run build:archive:bookmarks

      - name: Run
        run: npm run archive:bookmarks
        env:
          CI: true
          AIRTABLE_API: ${{secrets.AIRTABLE_API}}
          AIRTABLE_BOOKMARKS_ENDPOINT: ${{secrets.AIRTABLE_BOOKMARKS_ENDPOINT}}
          B2_APP_KEY_ID: ${{secrets.B2_APP_KEY_ID}}
          B2_APP_KEY: ${{secrets.B2_APP_KEY}}
          B2_BUCKET_ID: ${{secrets.B2_BUCKET_ID}}
          B2_BUCKET_NAME: ${{secrets.B2_BUCKET_NAME}}
