name: Archive Starred Repos

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  archive-starred-repos:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node 16.4.2
        uses: actions/setup-node@v2
        with:
          node-version: 16.4.2
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Compile
        run: npm run build:archive:starred-repos

      - name: Run
        run: npm run archive:starred-repos
        env:
          AIRTABLE_DEVELOPMENT_ENDPOINT: ${{secrets.AIRTABLE_DEVELOPMENT_ENDPOINT}}
          AIRTABLE_API: ${{secrets.AIRTABLE_API}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
