name: Archive Bookmarks

# on:
#   schedule:
#     - cron: '0 */2 * * *'

jobs:
  archive-bookmarks:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Compile
        run: npm run build:archive:bookmarks

      - name: Setup ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg

      - name: Run
        run: npm run archive:bookmarks
        env:
          CI: true
          AIRTABLE_API: ${{secrets.AIRTABLE_API}}
          AIRTABLE_BOOKMARKS_ENDPOINT: ${{secrets.AIRTABLE_BOOKMARKS_ENDPOINT}}
          B2_APP_KEY_ID: ${{secrets.B2_APP_KEY_ID}}
          B2_APP_KEY: ${{secrets.B2_APP_KEY}}
          B2_BUCKET_ID: ${{secrets.B2_BUCKET_ID}}
          B2_BUCKET_NAME: ${{secrets.B2_BUCKET_NAME}}
