name: Backup Hasura

on:
  schedule:
    - cron: '30 5 * * *'

jobs:
  backup-hasura:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node 16.15.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Compile
        run: npm run build:backup:hasura

      - name: Run
        run: npm run backup:hasura
        env:
          B2_APP_KEY_ID: ${{secrets.B2_APP_KEY_ID}}
          B2_APP_KEY: ${{secrets.B2_APP_KEY}}
          B2_BUCKET_ID: ${{secrets.B2_BUCKET_ID}}
          B2_BUCKET_NAME: ${{secrets.B2_BUCKET_NAME}}
          HASURA_ADMIN_SECRET: ${{secrets.HASURA_ADMIN_SECRET}}
          HASURA_ENDPOINT: ${{secrets.HASURA_ENDPOINT}}
