name: Backup Airtable

on:
  schedule:
    - cron: '0 23 * * *'

jobs:
  backup-airtable:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Compile
        run: npm run build:backup:airtable

      - name: Run
        run: npm run backup:airtable
        env:
          AIRTABLE_BOOKMARKS_ENDPOINT: ${{secrets.AIRTABLE_BOOKMARKS_ENDPOINT}}
          AIRTABLE_FAVORITES_ENDPOINT: ${{secrets.AIRTABLE_FAVORITES_ENDPOINT}}
          AIRTABLE_MEDIA_ENDPOINT: ${{secrets.AIRTABLE_MEDIA_ENDPOINT}}
          AIRTABLE_RECORDS_ENDPOINT: ${{secrets.AIRTABLE_RECORDS_ENDPOINT}}
          AIRTABLE_API: ${{secrets.AIRTABLE_API}}
          B2_APP_KEY_ID: ${{secrets.B2_APP_KEY_ID}}
          B2_APP_KEY: ${{secrets.B2_APP_KEY}}
          B2_BUCKET_ID: ${{secrets.B2_BUCKET_ID}}
          B2_BUCKET_NAME: ${{secrets.B2_BUCKET_NAME}}
